In [1]:
import numpy as np

x=np.random.randint(1,10,(3,3))
y=np.random.randint(1,10,(3,3))
print(x)
print(y)

[[8 6 7]
 [6 5 8]
 [4 4 5]]
[[4 1 2]
 [2 7 4]
 [4 6 7]]


In [11]:
a=np.arange(12).reshape(3,4)
b1=np.array([False,True,True])
b2=np.array([True,False,True,False])
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
a[:,b2]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [17]:
ans=np.sort(a)
ans

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
print(x)
print(y)

[[8 6 7]
 [6 5 8]
 [4 4 5]]
[[4 1 2]
 [2 7 4]
 [4 6 7]]


In [19]:
x=np.random.randint(1,10,(3,2))
y=np.random.randint(1,10,(2,3))
print(x)
print(y)

[[2 1]
 [1 7]
 [5 8]]
[[9 7 6]
 [4 3 7]]


In [33]:
y=np.transpose(y)
ans=x-y
print(ans)

[[-7 -3]
 [-6  4]
 [-1  1]]
