In [3]:
import numpy as np
a=[1,2,3]
b=np.array(a)
print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>


In [17]:
a=[1,2,3,1.5,'5']
b=np.array(a*3)
print(b)


['1' '2' '3' '1.5' '5' '1' '2' '3' '1.5' '5' '1' '2' '3' '1.5' '5']


In [19]:
b=np.ones(3,dtype=int)
b

array([1, 1, 1])

In [101]:
b=np.zeros((3,3),dtype=int)
b

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [23]:
b=np.ones((3,4),dtype=int)
b

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [26]:
b=np.full((3,4),100,dtype=int)
b

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [28]:
b=np.arange(2,13,4)
b

array([ 2,  6, 10])

In [30]:
b=np.arange(9)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [97]:
b=np.linspace(1,20)
print(b)
print(b[2]-b[1])
print(b[1]-b[0])
#0.3877551020408163

[ 1.          1.3877551   1.7755102   2.16326531  2.55102041  2.93877551
  3.32653061  3.71428571  4.10204082  4.48979592  4.87755102  5.26530612
  5.65306122  6.04081633  6.42857143  6.81632653  7.20408163  7.59183673
  7.97959184  8.36734694  8.75510204  9.14285714  9.53061224  9.91836735
 10.30612245 10.69387755 11.08163265 11.46938776 11.85714286 12.24489796
 12.63265306 13.02040816 13.40816327 13.79591837 14.18367347 14.57142857
 14.95918367 15.34693878 15.73469388 16.12244898 16.51020408 16.89795918
 17.28571429 17.67346939 18.06122449 18.44897959 18.83673469 19.2244898
 19.6122449  20.        ]
0.3877551020408163
0.3877551020408163


In [96]:
b=np.eye(7,7)*10
b

array([[10.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0., 10.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., 10.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0., 10.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., 10.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0., 10.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0., 10.]])

In [63]:
b=np.identity(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [79]:
b=np.random.rand(3,3)*100
b

array([[46.1311142 , 38.005484  , 36.51703306],
       [19.50897029, 15.6680661 , 83.33361604],
       [69.8415691 , 68.8080721 , 39.68178189]])

In [138]:
b=np.random.randint(1,10,4)

b

array([1, 4, 4, 7])

In [149]:
a=np.random.randint(1,20,(3,3))
a

array([[12,  2,  6],
       [15,  2, 10],
       [14,  9,  7]])

In [145]:
print(a)
print(b)

[11 15  8 16 12]
[1 4 4 7]


In [150]:
b=np.random.randint(1,30,(3,3))
b

array([[13, 28, 25],
       [20, 17, 27],
       [19, 25,  6]])

In [151]:
print(a)
print(b)

[[12  2  6]
 [15  2 10]
 [14  9  7]]
[[13 28 25]
 [20 17 27]
 [19 25  6]]


In [152]:
c=a+b
c

array([[25, 30, 31],
       [35, 19, 37],
       [33, 34, 13]])

In [153]:
c=a-b
c

array([[ -1, -26, -19],
       [ -5, -15, -17],
       [ -5, -16,   1]])

In [154]:
c=a/b
c

array([[0.92307692, 0.07142857, 0.24      ],
       [0.75      , 0.11764706, 0.37037037],
       [0.73684211, 0.36      , 1.16666667]])

In [155]:
c=a*b
c

array([[156,  56, 150],
       [300,  34, 270],
       [266, 225,  42]])

In [156]:
c=a**b
c

array([[ 1275068416,   268435456,  1174405120],
       [-1314489151,      131072,  -402653184],
       [ 1052246016,  -794958903,      117649]], dtype=int32)

In [157]:
c=a//b
c

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 1]], dtype=int32)

In [158]:
a=a+1
a

array([[13,  3,  7],
       [16,  3, 11],
       [15, 10,  8]])

In [160]:
b=b+10
b

array([[33, 48, 45],
       [40, 37, 47],
       [39, 45, 26]])

In [161]:
b=b-20
b

array([[13, 28, 25],
       [20, 17, 27],
       [19, 25,  6]])

In [172]:
b=np.array(b)
b

array([[14, 29, 26],
       [21, 18, 28],
       [20, 26,  7]])

In [173]:
b=b-10
b

array([[ 4, 19, 16],
       [11,  8, 18],
       [10, 16, -3]])

In [174]:
b>a

array([[False,  True,  True],
       [False,  True,  True],
       [False,  True, False]])

In [175]:
a>b

array([[ True, False, False],
       [ True, False, False],
       [ True, False,  True]])

In [178]:
a==b

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [181]:
print(a)
print(b)

[[13  3  7]
 [16  3 11]
 [15 10  8]]
[[ 4 19 16]
 [11  8 18]
 [10 16 -3]]


In [179]:
print(a.sum())
print(a.mean())
print(a.min())
print(a.argmin())
print(a.max())
print(a.argmax())

86
9.555555555555555
3
1
16
3


In [193]:
a[1,0]=14
print(a)

[[13 17  7]
 [14  0  8]
 [ 4  5  6]]


In [194]:
print(a.argmax())

1


In [195]:
print(a.argmin())

4


In [196]:
print(np.logical_or(a,b))
print(np.logical_and(a,b))
print(np.logical_not(a))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True False  True]
 [ True  True  True]]
[[False False False]
 [False  True False]
 [False False False]]


In [197]:
a>10

array([[ True,  True, False],
       [ True, False, False],
       [False, False, False]])

In [200]:
new_arr= a[(a>10)&(a<17)]
new_arr

array([13, 14])

In [201]:
c=b
c

array([[ 4, 19, 16],
       [11,  8, 18],
       [10, 16, -3]])

In [202]:
c=a
c

array([[13, 17,  7],
       [14,  0,  8],
       [ 4,  5,  6]])

In [203]:
d=['x','a','s']
d

['x', 'a', 's']

In [204]:
c=c[(c>10)]
c

array([13, 17, 14])

In [216]:
c[:2]=19
c

array([19, 19, 19, 18, 15, 15,  9, 18, 15, 15])

In [211]:
a=np.random.randint(1,30,10)
a


array([17, 10, 19, 18, 22, 22,  9, 18, 10, 10])

In [212]:
c=a
c

array([17, 10, 19, 18, 22, 22,  9, 18, 10, 10])

In [215]:
c[:3]=19
c[c>19]=10
c[c==10]=15
c

array([19, 19, 19, 18, 15, 15,  9, 18, 15, 15])

In [217]:
print(c[c==19])

[19 19 19]


In [220]:
i=np.where(c==19)
print(i)

(array([0, 1, 2], dtype=int64),)


In [221]:
d=['x','a','w','c','p','t','e','q','g','f']
d

['x', 'a', 'w', 'c', 'p', 't', 'e', 'q', 'g', 'f']

In [222]:
print(c)
print(d)

[19 19 19 18 15 15  9 18 15 15]
['x', 'a', 'w', 'c', 'p', 't', 'e', 'q', 'g', 'f']


In [227]:
i=np.where(c==19)
i
#print(d[i])

(array([0, 1, 2], dtype=int64),)

In [228]:
d=np.array(d)
d

array(['x', 'a', 'w', 'c', 'p', 't', 'e', 'q', 'g', 'f'], dtype='<U1')

In [229]:
i=np.where(c==19)
i
print(d[i])

['x' 'a' 'w']


In [230]:
a=np.random.randint(1,30,(3,3))
a

array([[ 6,  8, 20],
       [16, 18,  1],
       [17, 17, 22]])

In [231]:
a>7

array([[False,  True,  True],
       [ True,  True, False],
       [ True,  True,  True]])

In [233]:
a>17

array([[False, False,  True],
       [False,  True, False],
       [False, False,  True]])

In [234]:
bool_ind=a>17
bool_ind

array([[False, False,  True],
       [False,  True, False],
       [False, False,  True]])

In [235]:
ans=a[bool_ind]
ans

array([20, 18, 22])

In [236]:
c=a
c

array([[ 6,  8, 20],
       [16, 18,  1],
       [17, 17, 22]])

In [239]:
c[bool_ind]=100

In [240]:
c

array([[  6,   8, 100],
       [ 16, 100,   1],
       [ 17,  17, 100]])

In [245]:
bool_arr=c[2,:] == 17
print(bool_arr)

[ True  True False]


In [246]:
c[bool_arr]=200
c

array([[200, 200, 200],
       [200, 200, 200],
       [ 17,  17, 100]])

In [247]:
c=a
c

array([[200, 200, 200],
       [200, 200, 200],
       [ 17,  17, 100]])

In [248]:
a

array([[200, 200, 200],
       [200, 200, 200],
       [ 17,  17, 100]])

In [249]:
a=np.random.randint(1,30,(4,4))
a

array([[26, 14, 12, 28],
       [13,  2, 16,  5],
       [17,  3, 12,  8],
       [20, 25, 12,  8]])

In [250]:
c=a
c

array([[26, 14, 12, 28],
       [13,  2, 16,  5],
       [17,  3, 12,  8],
       [20, 25, 12,  8]])

In [255]:
bool_arr=c[:,2]==12
print(bool_arr)

[ True  True  True  True]


In [256]:
c

array([[26, 14, 12, 28],
       [13,  2, 12,  5],
       [17,  3, 12,  8],
       [20, 25, 12,  8]])

In [257]:
c[1,2]=16
c

array([[26, 14, 12, 28],
       [13,  2, 16,  5],
       [17,  3, 12,  8],
       [20, 25, 12,  8]])

In [259]:
bool_arr=c[:,2]==12
print(bool_arr)

[ True False  True  True]


In [261]:
c[bool_arr,2]=99
print(c)

[[26 14 99 28]
 [13  2 16  5]
 [17  3 99  8]
 [20 25 99  8]]


In [ ]:
c[:,2]==